name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIAQWNA63UOO5S3J42M
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin 048119078172.dkr.ecr.us-east-1.amazonaws.com

    - name: Build & Push
      run: |
        docker build -t house-price-api .
        docker tag house-price-api:latest <ECR-URL>
        docker push 048119078172.dkr.ecr.us-east-1.amazonaws.com/house-price-api:latest

    - name: Trigger App Runner Deployment
      run: |
        aws apprunner start-deployment --service-arn arn:aws:apprunner:us-east-1:048119078172:service/House_price_service/b014f9d010fd4143b8e62241b55b4dad
